destination: ./_site
lsi:         false
port:        4000
pygments:    true
markdown:    maruku
permalink:   date
maruku:
  use_tex:    false
  use_divs:   false
  png_dir:    images/latex
  png_url:    /images/latex
feed:         http://feeds.feedburner.com/EverydayRails
twitter:      http://twitter.com/everydayrails
facebook:     http://facebook.com/everydayrails
exclude:      [node_modules, scss, tmp, bower_components, .ruby-version, bower.json, Rakefile, gulpfile.js, Gemfile, Gemfile.lock, Guardfile]
