destination: ./_site
lsi: false
port: 4000
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    default_lang: html
    css_class: "highlight"
permalink: date
feed: https://leftofthe.dev/atom.xml
twitter: https://twitter.com/leftofthedev
facebook: https://facebook.com/leftofthedev
exclude:
  [
    node_modules,
    scss,
    tmp,
    .ruby-version,
    Gemfile,
    Gemfile.lock,
    drafts,
    public,
    src,
    mise.toml,
  ]
tag_page_layout: tags
tag_page_dir: tag
plugins: [jekyll-gist]
