backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "Posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: "md"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Excerpt", name: "excerpt", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "legacy-posts"
    label: "Posts (legacy)"
    folder: "_posts"
    create: false
    extension: "markdown"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Excerpt", name: "excerpt", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
